### ISSUE TITLE
Refactor Design

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#14]
## Value Proposition

**As a user**

**I want to** see a visually appealing and clear design

**so that** I can enjoy using the app

## Description

The app looks modern and provides a good user feedback overall

## Acceptance Criteria

- The app has a consistent, balanced and clear style.

## Tasks

- [x] Create feature branch `feature/refactor-design`
- [x] Delete "BackLink"-component and its integration in the bookmark page code
- [x] Change colors of background, navbar etc.
- [x] (Adjust titles for the input fields in the PlantForm-Component)
- [x] Ensure that the plant images are not displayed distorted.
- [x] Change font, (Roboto) adjust sizes
- [x] Add a sad flower icon on bookmark page if no plant is bookmarked
- [x] Adjust styles of filter and form components

** NOTES **

- Schriftart implementieren (Roboto) ☑️
- Buttons einheitlich machen ☑️
- Farbe Hintergrund und Nav Bar (white) ☑️
- Details Beschreibungstext kleinere Breite ☑️
- Ohne Beschreibungstext mehr Platz nach oben (Delete Button) ☑️
- Platz zwischen Icons und Text kleiner machen ☑️
- Edit Button bündig mit Karte ☑️
- Plant Name Umbruch falls zu lang ☑️
- Bilder Formatierung auf Details Page (ohne Verzerrung) ☑️
- Image Upload stylen ☑️
- Filter springt mit Search Bar und so ☑️
- 
- https://react-icons.github.io/react-icons/search/#q=rose
- Blur Bg Details Buttons

**Comment by frush86** [comment]
"Add a sad flower icon on bookmark page if no plant is bookmarked" 🥹
