### ISSUE TITLE
Upload Plant Image

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#17]
## Value Proposition

**As a user**

**I want to** upload an image of a plant

**so that** I can use my own images. 

## Description

Copy-Paste Error, the Create-Form should not have a cancel button

![Image](https://github.com/user-attachments/assets/2600d086-cd03-4d4e-b593-6bac6af9f202)

## Acceptance Criteria

- The user can upload an image while creating or editing a plant
- Users can upload an image through the upload button
- If the user uploads an image the image name is displayed within the form element, right next to the upload button
- When the user clicks "Save," the data is saved, and the plant is displayed with the uploaded picture, regardless of whether the user is adding a new plant or editing an existing one.

## Tasks

- [ ] Create feature branch `feature/upload-image`
- [ ] Integrate an image upload feature with cloudinary in the form component
- [ ] Add an upload section in the form component
- [ ] Add a function to show the image name within the form element, after the user uploaded it
- [ ] Add function to show the image on the homepage and the details page

**Comment by StephMode** [comment]
Hi @cbuerger92 ,

great US overall! I really like how clear and straightforward the Value Proposition, Wireframes and Tasks are. 

Just two suggestions regarding the Acceptance Criteria:

> - Users can upload an image through the upload button, and the image name is displayed in the form

It might be helpful to specify exactly where in the form the user can see the newly uploaded image. Based on your wireframes, I assume that the image will be displayed within the image upload input element.

> - When the user clicks "Save," the data is saved, and the new plant is shown with the uploaded picture

Consider rephrasing this to include both cases - adding and editing a plant (see AC 1 in this US). This will clarify the behavior for both scenarios.
