### ISSUE TITLE
More Filter Options

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#18]
## Value Proposition

**As a user**

**I want to** have more filter criteria to choose from

**so that** i can specify my search

## Description

![Image](https://github.com/user-attachments/assets/86cc71ba-03c1-467d-9d2c-c3e63455ef75)

## Acceptance Criteria

- There are options to filter the plants based on different criteria: light need, water need, fertiliser season
- The user can select one or several filters at the same time
- A number that counts the selected filters should be displayed within the button 
- The user can set the filters and the PlantList should update immediately

## Tasks

- [ ] Create feature branch `feature/more-filters`
- [ ] Add further filters to the existing list like "Water needs" and "Fertiliser Season"
- [ ] Implement a counter to the filter that reflects the number of active filters

**Comment by StephMode** [comment]
Hey @cbuerger92 ,

that's a very good US already. The value proposition and the wireframe are both straight to the point!

I would just have some suggestions regarding the Acceptance Criteria and Tasks:

**Regarding the Acceptance Criteria**

> The filter options have been expanded to allow selection based on water requirements and fertilization season. These new filters offer users a more targeted search, making it easier to find plants according to their specific care needs.

The AC should describe the feature from the user's perspective and the user is usually not aware of features from past versions. Also, I'd suggest to refrain from putting too much emphasis on the value add of the feature, since the AC should describe the UX and not advertise it. Thus, I'd suggest to rephrase this AC to something like this:

- There are options to filter the plants based on diffrent criteria: Light Need, Water Need, Fert Season.
- The User can select one or several filters at the same time.


**Regarding the Tasks**

I'd suggest to rephrase the tasks so that they reflect what needs to be done instead of decribing the feature.

Examples:

> The filter counter should react and count with every click

Implement a counter to the filter that reflects the number of active filters.

This would summarize Task 3 and 4. You could then leave this one out:

> ~With each click, the PlantList should update according to the filtered criteria~
