### ISSUE TITLE
Reset Button Form 

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#29]
## Value Proposition

**As a user**

**I want to** reset the entries

**so that** I don't have to delete everything manually myself.

## Description

![Image](https://github.com/user-attachments/assets/d82eecb5-66d8-4b98-adcf-4e8176323242)

## Acceptance Criteria

- The reset button is available in the "Create new Plant".
- The button resets all fields in the form to empty fields.
- The reset occurs without reloading the page or changing navigation.
- The reset button includes an appropriate icon and is placed in the top left corner near the form title.

## Tasks

- [ ] Create feature branch `feature/reset-button`
- [ ] Add and position a reset button with an eraser icon in the top left corner near the form title in the "Create" form
- [ ] Implement functionality to clear all input fields in the "Create" form
