### ISSUE TITLE
#1: Plant List

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#3]
# Plant List

## Value Proposition

**As a user**

**I want to** browse a list of plants,

**so that** I can discover new plants and learn about their care requirements.

## Description

![Image](https://github.com/user-attachments/assets/370578e1-fd27-44a4-94f3-f944043264f2)

## Acceptance Criteria

- The homepage displays the app title.
- The homepage displays a list of plants.
- The plant list is headlined with its purpose.
- Each plant listing includes:
  - Plant name
  - Plant botanical name
  - Plant image
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/plant-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/plants.json)
  - [ ] Add an `imageUrl` for each plant, for example from [unsplash.com](unsplash.com)
- [ ] Display the app title and the headline
- [ ] Set up a component for displaying a single plant card
- [ ] Display name, botanical name and image on each plant card
- [ ] Map plant card for each entry
- [ ] Make the side vertical scrollable

**Comment by JessicaLoers** [comment]
Well done ✅
