### ISSUE TITLE
Filter for Bookmarks

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#32]
## Filter Bookmarks

**As a user**

**I want to** filter my bookmarked plants

**so that** I can find a specific bookmarked plant based on its characteristics

## Description

![Image](https://github.com/user-attachments/assets/5b1dd41d-806c-45c6-bbd9-fb9f8e56621c)

## Acceptance Criteria
- There is a button on the bookmark page which opens the filter for the bookmarked plants.
- There are options to filter the plants based on different criteria: light need, water need, fertiliser season
- The user can select one or several filters at the same time
- A number that counts the selected filters should be displayed within the button 

## Tasks

- [ ]  Create feature branch 'feature/filter-for-bookmarks'
- [ ] Rerender the filter component on the bookmark page
- [ ] Add the functionality to only filter the bookmarked plants
