### ISSUE TITLE
#2: Plant Details

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#4]
# Plant Details

## Value Proposition

**As a user**

**I want to** access detailed information about each plant,

**so that** I can get a better understanding of the plant's needs and care requirements.

## Description

![Image](https://github.com/user-attachments/assets/6660a134-2eeb-4137-bea7-21bc15b2ba9d)

## Acceptance Criteria

- Each image of the plant card in the plant list has a link/button to a details page.
- Each details page contains:
  - Plant name
  - Plant botanical name
  - Plant image
  - Plant description
  - Plant light needs
  - Plant water needs
  - Plant fertiliser season
- The water needs, light needs and fertiliser seasons are visualised with fitting icons (e.g. empty or full droplets of water).
- The detailed view includes a “back” link, allowing users to easily navigate back to the plant list.

## Tasks

- [ ] Create feature branch `feature/plant-details`
- [ ] On the plant list link each plant card to its own detail page, if the details button is clicked
- [ ] Create a plant details page
- [ ] Set up a component to display name, botanical name, image, description, light needs, water needs and fertiliser season
- [ ] The water needs, light needs and fertiliser seasons are visualised with fitting icons
- [ ] On top of the details page display a button that redirect to the homepage

**Comment by JessicaLoers** [comment]
Please add the wireframe that shows me as a user how to get from the homepage to the details page of the respective plant. ✨
