### ISSUE TITLE
Mark Plants as Owned

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#5]
# Mark Plants as Owned

## Value Proposition

**As a user**

**I want to** mark the plants I own,

**so that** I can easily track and manage the care of my personal collection.

## Description

![Image](https://github.com/user-attachments/assets/e1394745-ef43-4150-85fc-0059d2be650e)

## Acceptance Criteria

- Each listed plant includes a “Mark as Owned” option.
- Clicking the “Mark as Owned” button of an unmarked plant adds it to the “My Plants” list.
- Clicking the same button again removes the plant from the “My Plants” list.
- The “My Plants” list is displayed on a separate page dedicated to owned plants.
- There is a clearly visible navigation bar with a button for the "My Plants"-page on all pages
- Owned plants are visually highlighted by a distinct icon or style to differentiate them from unowned plants.
- If there are no owned plants in the “My Plants” list, a message is displayed to the user indicating that no plants have been marked as owned.

## Tasks

- [ ] Create feature branch `feature/mark-as-owned`
- [ ] Add a toggle-button to the top of the plant cards visually highlighted by a distinct icon or style
- [ ] The button add or remove the plant from the “My Plants” list
- [ ] Create a new page for "My Plants"
- [ ] Set up a component for displaying a navbar that direct to the  "My Plants" list on all pages
- [ ] On top of the "My Plants" page display a button that redirect to the homepage
- [ ] An messages occures if no owned plants are saved

**Comment by JessicaLoers** [comment]
Nice 👍 ✅
