### ISSUE TITLE
Create Plant

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#6]
# Create Plant

## Value Proposition

**As a user**

**I want to** create and store new plants,

**so that** I can personalise and expand the plant selection to better reflect my collection and preferences.

## Description

![Image](https://github.com/user-attachments/assets/fc7d294c-2f90-4991-923e-09c4a3b4d182)

## Acceptance Criteria

- A button is displayed at the top of the homepage for open or close the form with its purpose.
- A form for adding plants is displayed at the top of the homepage, when the button is clicked.
- The form must include labelled fields for:
  - Plant name
  - Plant botanical name
  - Plant description
  - Plant light needs
  - Plant water needs
  - Plant fertiliser season
- The following fields are mandatory:
  - Plant name
  - Plant botanical name
  - Plant light needs
  - Plant water needs
- The light needs are selected via radio buttons with the options: Full Sun, Partial Shade, Full Shade.
- The water needs are selected via radio buttons with the options: Low, Medium, High.
- The fertiliser season is selected via checkboxes, allowing multiple selections with the options: Spring, Summer, Autumn, Winter.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new plant is added to the top of the plant list.

## Tasks

- [ ] Create feature branch `feature/create-plant`
- [ ] Create a toggle-button at the top of the homepage for open or close the form
- [ ] Set up a form component with the name `PlantForm` 
- [ ] There are text input fields for name, botanical name and description
- [ ] There are radio buttons light needs, water needs
- [ ] There are checkboxes for the fertiliser season
- [ ] Check the mandatory fields before submit (name, botanical name, light needs, water needs)
- [ ] If not all mandatory fields are filled display an error message
- [ ] If the form is submitted, add the new plant to the top of the plant list
- [ ] Refresh the site, so the user can the change instantly

> 💡 It is not yet possible to add images at this stage. For this reason, a placeholder image should be saved when creating a plant.

**Comment by JessicaLoers** [comment]
Well done 🙌✅
