### ISSUE TITLE
Delete Plant

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#7]
# Delete Plant

## Value Proposition

**As a user**

**I want to** delete plants that are no longer relevant,

**so that** I can maintain a clean and organised plant list, ensuring it’s always up to date.

## Description

![Image](https://github.com/user-attachments/assets/280c65bb-b51c-4f6d-84b1-7f253261eb55)

## Acceptance Criteria

- Each plant details view includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the user is immediately redirected to the overview of all plants, and the plant is removed from the list.
- If all plants are deleted, a message appears indicating that there are no plants and providing an option to add new ones.

## Tasks

- [ ] Create feature branch `feature/delete-plant`
- [ ] Display a delete toggle button at the bottom on each detail page 
- [ ] Introduce a state to handle the confirmation message, show a new button for confirmation and change the name of the delete button to cancel
- [ ] If the cancel toggle-button is pressed the site will go back to default
- [ ] If the confirmation button is pressed the plant will be deleted and the user will be redirect to the plant list 
- [ ] Show a error message if there are no plants left

**Comment by JessicaLoers** [comment]
Well done ✅

**Comment by StephieTack** [comment]
Hi, very clean code! :)  One additional remark: In your AC and Wireframe there is a point for showing a message when you click on the delete button: "Clicking the delete option triggers a confirmation dialog." I can't find it in your code. Could you check it?
