### ISSUE TITLE
Update Plant

### ISSUE THREAD

**Issue by Bianca-Gundel** [Bianca-Gundel/PlantPal#8]
# Update Plant

## Value Proposition

**As a user**

**I want to** update the details of existing plants,

**so that** they reflect the most accurate and relevant information.

## Description

![Image](https://github.com/user-attachments/assets/e32df0b7-041e-460e-8c90-a1b0351ef76a)

## Acceptance Criteria

- Each plant details page includes an easily accessible edit option.
- Clicking the edit option opens a new page with a form pre-filled with the plant's existing details for modification.
- The form allows for edits to all plant details, including:
  - Plant name
  - Plant botanical name
  - Plant description
  - Plant light needs
  - Plant water needs
  - Plant fertiliser season
- The following fields are mandatory:
  - Plant name
  - Plant botanical name
  - Plant light needs
  - Plant water needs
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is immediately redirected to the details page of the edited plant, and the changes are saved and reflected.

## Tasks

- [ ] Create feature branch `feature/update-plant`
- [ ] Add Button with Icon in it to link to the Edit Page
- [ ] Create Edit Plant Page
- [ ] Display Headline "Edit Plant"
- [ ] Rerender Form Component (prefilled)
- [ ] Check the mandatory fields before submit (name, botanical name, light needs, water needs)
- [ ] Rerender two Buttons from the Button Component (Save and Cancel)
- [ ] Add onClick Events to either save the edits or to cancel 
- [ ] The Save Button links to updated Details Page which includes the edits
- [ ] The Cancel Button links to the Details Page without any changes

> 💡 It is not yet possible to edit images at this stage.
